[package]
name = "stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timely = {version = "0.12", features=["bincode"]}
differential-dataflow = "0.12"
abomonation = "0.7.3"
abomonation_derive = "0.5"
datafusion-expr.workspace = true
datafusion-substrait.workspace = true
serde = {version = "1.0", features = ["derive"]}
datatypes = { path = "../datatypes" }