[package]
name = "stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# use version from crates.io for now to prevent version slewing
# disable default-features which include `abomonaion` which we don't need for IPC
# timely = {version = "0.12.0", default-features = false, features = ["bincode"]}
# differential-dataflow = "0.12.0"
timely = "0.12.0"
differential-dataflow = "0.12.0"
# TODO: fork later for fixed version git dependency
# timely = { git = "https://github.com/TimelyDataflow/timely-dataflow", default-features = false }
# differential-dataflow = { git = "https://github.com/TimelyDataflow/differential-dataflow", rev ="99fa67db"}
datafusion-expr.workspace = true
datafusion-substrait.workspace = true
serde = { version = "1.0", features = ["derive"] }
datatypes = { path = "../datatypes" }
